### ISSUE TITLE
Idea: multiple rows of X items

### ISSUE THREAD

**Issue by CodeWithDennis** [Muetze42/nova-radio-field#1]
**Example:**

`->colums(3)`

Radio 1 | Radio 2 | Radio 3
Radio 4 | Radio 5 | Radio 6
Radio 7 | Radio 8 | Radio 9

Great package BTW!

**Comment by Muetze42** [comment]
Thanks. I was surprised that there wasn't something like that for Nova 4 yet. (At least I have not found anything)

I'm currently working on a big extension for the Nova menu.

In the course of the week this package gets an update.

**Comment by Muetze42** [comment]
Huhu,

I discarded the method colums in this way to give the field more flexibility .

Of course it is still possible to build a grid:
https://github.com/Muetze42/nova-radio-field#example-creating-grid-like-3rd-preview  
![grid](https://user-images.githubusercontent.com/26193232/234968529-43dcd2f8-74ef-4789-b18f-2fa99dc477ef.png)

I hope this solution is OK?

**Comment by CodeWithDennis** [comment]
Awesome, great solution!
