### ISSUE TITLE
Updating / Replicating

### ISSUE THREAD

**Issue by CodeWithDennis** [Muetze42/nova-radio-field#14]
When updating / replicating the value will fallback to the first option when using `dependsOn`.

```PHP
 Radio::make(__('Methode'), 'method')
      ->options(CompanyAgreementMethodEnum::options())
      ->default(CompanyAgreementMethodEnum::Exclusive->value)
      ->dependsOn(['type'], function (Select $field, NovaRequest $request, FormData $formData) {
           if ($formData->type == CompanyAgreementTypeEnum::Phone->value) {
              $field->options([CompanyAgreementMethodEnum::Exclusive->value => CompanyAgreementMethodEnum::Exclusive->label()]);
           }
        })
->inline()
->gap(3),
```

See video (im refreshing the page and you can see it falling back to first option)
https://github.com/Muetze42/nova-radio-field/assets/23448484/13ff3b9e-1643-4d09-8d58-2e324057df7e

In this case im editing the Resource and the 'Methode (method)' should be the second option.

**Comment by Muetze42** [comment]
I'll take a look at it over the course of the week. Please be patient.

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-radio-field/releases

**Comment by CodeWithDennis** [comment]
Thanks it solved it!
