### ISSUE TITLE
When used in action, the radio field is displayed as Select

### ISSUE THREAD

**Issue by wamesro** [Muetze42/nova-radio-field#16]
`laravel/nova`: 4.24.3
`norman-huth/nova-radio-field`: 1.1.6

When used in action, the radio field is displayed as Select
![Snímka obrazovky 2023-05-19 o 15 06 41](https://github.com/Muetze42/nova-radio-field/assets/5340873/2e90eb3a-5e1b-4bf4-a7e2-cf48bd0022a7)

- run `php artisan nova:action RadioExampleAction`
- add field to action
```
public function fields(NovaRequest $request): array
{
    return [
        Radio::make(__('Type'), 'type')
            ->help(__('Help Text'))
            ->options([
                'S' => __('Small'),
                'M' => __('Medium'),
                'L' => __('Large'),
            ])->inline(),
    ];
}
```
- add action to resource
```
    public function actions(NovaRequest $request): array
    {
        return [
            RadioExampleAction::make()
        ];
    }
```

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-radio-field/releases

**Comment by wamesro** [comment]
It still doesn't work. 
Is there a proven procedure?

**Comment by Muetze42** [comment]
Have You installed the current Version?

Action Code:  
https://github.com/Muetze42/laravel-nova-demo-app/blob/main/app/Nova/Actions/RadioAction.php

Action on index:
https://nova-demo.huth.it/resources/nova-radio-field-radios

Action on detail:
https://nova-demo.huth.it/resources/nova-radio-field-radios/1

**Comment by Muetze42** [comment]
Maybe the old JavaScript is still in the browser cache?

For this problem I have developed this package:  
https://github.com/Muetze42/nova-assets-versioning

**Comment by wamesro** [comment]
I have already discovered the problem

This is how it works
```
public function actions(NovaRequest $request): array
{
    return [
        new ProductVariantExpedition()
    ];
}
```

and when using Inline Actions it shows as Select
[https://nova.laravel.com/docs/4.0/actions/registering-actions.html#inline-actions](https://nova.laravel.com/docs/4.0/actions/registering-actions.html#inline-actions)
```
public function actions(NovaRequest $request): array
{
    return [
        (new ProductVariantExpedition())->showInline()
    ];
}
```

**Comment by Muetze42** [comment]
Strange. For me it also works with `showInline()`

Can you test what happens when you add this method to the package file `src/Radio.php` ?

```php
class Radio extends Select
{
    // ...

    protected function isAction(): bool
    {
        if (!isset($this->isAction)) {
            $this->isAction = str_ends_with($this->getRequest()->path(), '/actions') || str_ends_with($this->getRequest()->path(), 'nova-api/nova-radio-field-radios');
        }

        return $this->isAction;
    }

    // ...
}
```

**Comment by wamesro** [comment]
It only works for bulk actions after checking the checkbox on the left, but after clicking on the 3 dots it is still Select

It works the same way in your demo
https://nova-demo.huth.it/resources/nova-radio-field-radios

https://github.com/Muetze42/nova-radio-field/assets/5340873/c2662187-6682-41f4-928d-ac413776479a

**Comment by Muetze42** [comment]
Ah. I see. The action path is not used there at all.

I'll have to think of something else. I guess I'll have to rewrite it so that the select is not used for detail & index. 

But will be something only tonight.

**Comment by wamesro** [comment]
Alright, good luck ;-)
but it's a great package

**Comment by Muetze42** [comment]
I was surprised that there is no radio field. Then I thought to myself, that is quickly done. But first that with `dependsOn`, then with the filters. If I had known that before. 😂

https://github.com/Muetze42/nova-radio-field/releases

**Comment by wamesro** [comment]
Great, now it works in action as well
