### ISSUE TITLE
Idea: Default value

### ISSUE THREAD

**Issue by Rtsss17** [Muetze42/nova-radio-field#2]
Hi is possible to make the default option like the old package for Nova 3?

**Example:**

```
Radio::make(__('Radio'), 'select')
    ->options([
        'S' => __('Small'),
        'M' => __('Medium'),
        'L' => __('Large'),
    ])
    ->default('L')
```

Thank you for this package!

**Comment by Muetze42** [comment]
There is an update planned this week. I'll include it right away, of course.

**Comment by Muetze42** [comment]
The release is out. Now the `default` method is processed.

https://github.com/Muetze42/nova-radio-field#default-value

https://github.com/Muetze42/nova-radio-field/releases
