### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by CodeWithDennis** [Muetze42/nova-radio-field#20]
**Not sure if this is on my end but since the new Nova update im getting the following error:**

`Illegal offset type in isset or empty` -> `vendor/norman-huth/nova-radio-field/src/Radio.php` -> line: `244`

```PHP
->dependsOn(['type'], function (Radio $field, NovaRequest $request, FormData $formData) {
   if ($formData->type == 'test') { $field->options('test'=> 'Test']); }
})
```

**Error occurs when using:**
[v4.25.0 (Silver Surfer)](https://nova.laravel.com/releases/4.25.0)

**Comment by Muetze42** [comment]
Tested with Nova 4.25.0 and 4.25.1 and Radio field 1.1.9.


https://nova-demo.huth.it/resources/nova-radio-field-radios/3/edit

https://github.com/Muetze42/laravel-nova-demo-app/blob/main/app/Nova/Resources/NovaRadioFieldRadio.php#L197

---

You have a syntax error:
```php
->dependsOn(['type'], function (Radio $field, NovaRequest $request, FormData $formData) {
    if ($formData->type == 'test') { $field->options(/* Missing --> */ [ /* <-- Missing */'test'=> 'Test']);}
})
```

**Comment by CodeWithDennis** [comment]
Yea sorry i edited the code only in this message (not actually code) that doesn't seem to be the problem. 
Actual problem is no longer present when using [v4.24.4](https://nova.laravel.com/releases/4.24.4)

Have you tried using a Radio `DependsOn` on another Radio?

**Comment by CodeWithDennis** [comment]
Have you tried using the Radio fields on another Radio field?

**Comment by Muetze42** [comment]
Sorry that it takes a while at the moment. I am actually on vacation.  🏝️

Live:
https://nova-demo.huth.it/resources/nova-radio-field-radios/5/edit

Code:
https://github.com/Muetze42/laravel-nova-demo-app/blob/main/app/Nova/Resources/NovaRadioFieldRadio.php#L201

Dependencies of the Demo App:
![image](https://github.com/Muetze42/nova-radio-field/assets/26193232/26a795b7-b386-4f83-92fd-c6fa8405e0f9)

**Comment by CodeWithDennis** [comment]
Once i am upgrading to the new Nova Version: `Upgrading laravel/nova (4.24.4 => 4.25.1)` see following video:

https://github.com/Muetze42/nova-radio-field/assets/23448484/7157ce22-211c-4d3f-969e-28bda42db340


Don't have to look now tho, enjoy the holidays =)
