### ISSUE TITLE
Resource is not updated correctly, when 0 is used as an option key

### ISSUE THREAD

**Issue by b-ssr** [Muetze42/nova-radio-field#21]
When I set 0 (zero) as one of the option keys (as shown in the example below) and select the corresponding option to update the resource, it fails to update. The option with the key 0 (zero) is ignored, and the first option is used instead.

`Radio::make('Status', 'status')->options(['1' => 'Show', '0' => 'Hide']);`

Is this the expected behavior or is it a bug?

**Comment by Muetze42** [comment]
Sorry. Overlooked and just realised it myself. But it won't be until this weekend.

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-radio-field/releases
